#! /bin/bash

# Image Preseeder, a tool to create preseeded Linux installation images
# Copyright 2013 Johannes Lehtinen
#
# Licensed under the MIT License, see LICENSE.md.

SCRIPTNAME=init-autotools

# Set up error handling
error () {
    echo "ERROR: $SCRIPTNAME: $1" 1>&2
    exit 1
}
set -e
trap 'error "Error in line $LINENO"' ERR

# Test that we are in correct directory
test -f image-preseeder.in \
    || error "In wrong working directory (image-preseeder.in not found)"

# Initialize autotools verbosely
set -x
aclocal
autoconf
automake --add-missing

# vim:si:sw=4:sta:et
