# Image Preseeder, a tool to create preseeded Linux installation images
# Copyright 2013 Johannes Lehtinen
#
# Licensed under the MIT License, see LICENSE.md.

# List of examples
EXAMPLES = ubuntu-server-install

# Targets used for examples
EXAMPLE_TARGETS = examples clean-examples

$(EXAMPLE_TARGETS):
	for example in $(EXAMPLES); do \
	    $(MAKE) -C $$example $@ || exit 1; \
	done

.PHONY: $(EXAMPLE_TARGETS)
