#! /bin/sh

# Abort on error
set -e

# Install VirtualBox guest utilities and kernel modules
apt-install virtualbox-guest-dkms virtualbox-guest-utils \
    || apt-install virtualbox-ose-guest-dkms virtualbox-ose-guest-utils

# Install and enable executor
cp /cdrom/image-preseeder/image-preseeder-executor /target/etc/init.d
in-target update-rc.d image-preseeder-executor start 99 2 3 4 5 . stop 99 0 1 6 .
